<?php

########################################################################
# Extension Manager/Repository config file for ext: "bgm_vrt"
#
# Auto generated by Extension Builder 2012-04-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'bgm Visual Regression Testing',
    'description' => 'Visual regression testing with PhantomCSS',
    'category' => 'Plugin',
    'author' => 'Marco Huber',
    'author_email' => 'mail@marco-huber.de',
    'author_company' => 'bgm websolutions GmbH & Co. KG',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.0.0-7.9.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);

?>